// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRyLUm8Vmgne4UBFjlAe4FwGI5VuOPS8A',
    appId: '1:72623827903:android:8daf39f5f1011b09300f0a',
    messagingSenderId: '72623827903',
    projectId: 'moody-c9329',
    databaseURL: 'https://moody-c9329-default-rtdb.firebaseio.com',
    storageBucket: 'moody-c9329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEcXohp9b6Nr0bG6Js2TtoiaoIIWDTw0',
    appId: '1:72623827903:ios:c5208c7d8988e060300f0a',
    messagingSenderId: '72623827903',
    projectId: 'moody-c9329',
    databaseURL: 'https://moody-c9329-default-rtdb.firebaseio.com',
    storageBucket: 'moody-c9329.firebasestorage.app',
    iosBundleId: 'com.example.moody',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQZeqxxXFOf5c5flyHGBTFWCj21qbSFs',
    appId: '1:72623827903:web:e5775df0d44d9056300f0a',
    messagingSenderId: '72623827903',
    projectId: 'moody-c9329',
    authDomain: 'moody-c9329.firebaseapp.com',
    databaseURL: 'https://moody-c9329-default-rtdb.firebaseio.com',
    storageBucket: 'moody-c9329.firebasestorage.app',
    measurementId: 'G-ZBYDVNG5VX',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtQZeqxxXFOf5c5flyHGBTFWCj21qbSFs',
    appId: '1:72623827903:web:d94470291ba52db6300f0a',
    messagingSenderId: '72623827903',
    projectId: 'moody-c9329',
    authDomain: 'moody-c9329.firebaseapp.com',
    databaseURL: 'https://moody-c9329-default-rtdb.firebaseio.com',
    storageBucket: 'moody-c9329.firebasestorage.app',
    measurementId: 'G-9T4DNBENMZ',
  );

}